"""Add RelationshipAttribute model and extra columns to Relationship

Revision ID: 0cb6d94c0138
Revises: 72a2787d6f2a
Create Date: 2025-03-02 14:55:16.163565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cb6d94c0138'
down_revision = '72a2787d6f2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationship_attribute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('relationship_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationship.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.add_column(sa.Column('effective_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relationship', schema=None) as batch_op:
        batch_op.drop_column('effective_date')

    op.drop_table('relationship_attribute')
    # ### end Alembic commands ###
