"""Add new fields to Company model

Revision ID: 72a2787d6f2a
Revises: 
Create Date: 2025-03-01 16:24:38.861753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72a2787d6f2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('registered_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('company_status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('incorporation_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('incorporation_date')
        batch_op.drop_column('company_status')
        batch_op.drop_column('registered_address')

    # ### end Alembic commands ###
